# Generated by Django 4.1.3 on 2022-12-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="date_time",
            field=models.CharField(max_length=128, verbose_name="date_time"),
        ),
        migrations.AlterField(
            model_name="board",
            name="temp",
            field=models.IntegerField(verbose_name="temperature"),
        ),
    ]
