# Generated by Django 4.1.3 on 2022-12-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_alter_board_date_time_alter_board_temp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="date_time",
            field=models.DateTimeField(verbose_name="date_time"),
        ),
    ]
