# Generated by Django 4.1.3 on 2022-12-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_alter_board_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="hex_color",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="hex"
            ),
        ),
    ]
